spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.117.106.178:3306/ciep
    username: ciep
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: file:${web.upload-path}

web:
  upload-path: C:\\Users\\CL\\Desktop\\data